export const scholarshipByCountry = [
  {
    country: "USA",
    scholarships: 8547,
    avgAmount: 25000,
    competitiveness: 85,
    tier: "REACH",
    universities: 4500,
  },
  {
    country: "Canada",
    scholarships: 3420,
    avgAmount: 18000,
    competitiveness: 72,
    tier: "MATCH",
    universities: 1500,
  },
  {
    country: "UK",
    scholarships: 2890,
    avgAmount: 22000,
    competitiveness: 88,
    tier: "REACH",
    universities: 1200,
  },
  {
    country: "Australia",
    scholarships: 2145,
    avgAmount: 20000,
    competitiveness: 75,
    tier: "MATCH",
    universities: 900,
  },
  {
    country: "Germany",
    scholarships: 1678,
    avgAmount: 15000,
    competitiveness: 68,
    tier: "SAFETY",
    universities: 700,
  },
  {
    country: "Netherlands",
    scholarships: 1234,
    avgAmount: 17000,
    competitiveness: 70,
    tier: "MATCH",
    universities: 500,
  },
  {
    country: "Sweden",
    scholarships: 892,
    avgAmount: 16000,
    competitiveness: 65,
    tier: "SAFETY",
    universities: 300,
  },
  {
    country: "Singapore",
    scholarships: 1456,
    avgAmount: 28000,
    competitiveness: 92,
    tier: "REACH",
    universities: 300,
  },
  {
    country: "Hong Kong",
    scholarships: 945,
    avgAmount: 26000,
    competitiveness: 89,
    tier: "REACH",
    universities: 250,
  },
  {
    country: "Switzerland",
    scholarships: 567,
    avgAmount: 30000,
    competitiveness: 95,
    tier: "REACH",
    universities: 150,
  },
  {
    country: "New Zealand",
    scholarships: 678,
    avgAmount: 19000,
    competitiveness: 72,
    tier: "MATCH",
    universities: 180,
  },
  {
    country: "Ireland",
    scholarships: 456,
    avgAmount: 16000,
    competitiveness: 68,
    tier: "SAFETY",
    universities: 120,
  },
]
